version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'monthly'
    labels:
      - 'x:size/tiny'
    groups:
      github-actions:
        patterns:
          - '*'
  # Keep dependencies for Composer up-to-date
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: 'monthly'
    labels:
      - 'x:size/tiny'
    groups:
      github-actions:
        patterns:
          - '*'
